#version: 0.0
#os: linux
#
#files:
#  - source: /
#    destination: /home/ubuntu/bucket-back
#permissions:
#  - object: /home/ubuntu/bucket-back/
#    owner: ubuntu
#    group: ubuntu
#hooks:
#  AfterInstall:
#    - location: scripts/deploy.sh
#      timeout: 60
#      runas: ubuntu
