set
FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE bucket_items;
TRUNCATE TABLE feed_items;
TRUNCATE TABLE feed_likes;
TRUNCATE TABLE inventory_items;
TRUNCATE TABLE members_items;
TRUNCATE TABLE voters;
TRUNCATE TABLE buckets;
TRUNCATE TABLE comments;
TRUNCATE TABLE feeds;
TRUNCATE TABLE inventories;
TRUNCATE TABLE reviews;
TRUNCATE TABLE votes;
TRUNCATE TABLE items;
TRUNCATE TABLE members;
set
