name: Java CICD with Gradle

on:
  push:
    branches:
      - feature/CICD-test
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: read

jobs:
  set-variable:
    runs-on: [self-hosted, loadbalancer-server] # Self-hosted, 'loadbalancer-server' 라벨을 가진 서버에서 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Blue Environment
        id: check-blue
        run: |
          IS_BLUE_ENV=$(sh /usr/local/bin/scripts/is_blue_env.sh)
          echo "IS_BLUE_ENV=$IS_BLUE_ENV" >> $GITHUB_ENV
        shell: bash

      - name: Print Environment
        run: |
          echo "IS_BLUE_ENV is ${{ env.IS_BLUE_ENV }}"

